config/routes.rb
Rails.application.routes.draw do


  root :to => "presentation_page#index"
  resources :password_resets
  get 'open_hub/similar', :to => "projects#similiar_open_hub_projects"

  resources :projects do
    get 'most_favorited', on: :collection
    get 'recent', on: :collection
    resources :ownership_requests, :controller => "projects/ownership_requests"
    resources :comments, :controller => "projects/comments"

    resources :users, :controller => "projects/users"
    post :favorite, :to =>"projects/favorites#create"
    delete :favorite, :to =>"projects/favorites#destroy"
    
    resources :widgets do
      resources :comments, :controller => "widgets/comments"
=begin 
        collection do
          put :approve
        end
=end
    end
  end

  #Comment Moderation:
  get '/projects/:project_id/widgets/:widget_id/moderate(.:format)', to: 'widgets/comments#moderate', as: 'moderate'
  put '/projects/:project_id/widgets/:widget_id/comments', to: 'widgets/comments#approve', as: 'approve_comments'
  #resources :widgets
  resources :forums do
    #this is for passing the project_id to the forum that's being created
    resources :topics do
      resources :messages
    end
  end
  
  put 'forums/new/:project_id' => 'forums#create', as: 'create_forum'
  resources :widget_comments, :controller => "widgets/comments"
  resources :project_comments, :controller => "projects/comments", only: [:create]
  resources :sessions

  # Oauth Related code
	get 'auth/:provider/callback', to: 'omni_auth_login#create'
  get 'auth/failure', to: redirect('/')
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  delete 'signout' => 'sessions#destroy'

  #Favoriting project related code:
  post "/users/favorite_project/:project_id" => "users#favorite_project"
  post "/users/disfavorite_project/:project_id" => "users#disfavorite_project"

  resources :users do
    member do
      get :confirm_email
    end
  end

  #tabs related code:
  get '/projects/:id/start',     to: 'projects#start',     as: 'start'
  get '/projects/:id/community', to: 'projects#community', as: 'community'
  get '/projects/:id/workspace', to: 'projects#workspace', as: 'workspace'
  get '/projects/:id/code',      to: 'projects#code',      as: 'code'
  get '/projects/:id/changes',   to: 'projects#changes',   as: 'changes'
  get '/projects/:id/success_stories',   to: 'projects#success_stories',   as: 'success_stories'
  
end

app/views/visitor/_footer.html.erb
<footer class="page-copyright page-copyright-inverse">
  <p>©<%=Date.today.year%> FlossCoach</p>
  <div class="social">
    <a class="btn btn-icon btn-pure" href="javascript:void(0)">
      <i class="icon bd-twitter" aria-hidden="true"></i>
    </a>
    <a class="btn btn-icon btn-pure" href="javascript:void(0)">
      <i class="icon bd-facebook" aria-hidden="true"></i>
    </a>
    <a class="btn btn-icon btn-pure" href="javascript:void(0)">
      <i class="icon bd-google-plus" aria-hidden="true"></i>
    </a>
  </div>
</footer>

app/views/visitor/_header.html.erb
<nav class="site-navbar navbar navbar-default navbar-fixed-top navbar-mega navbar-inverse"
role="navigation">
<div class="navbar-header">
  <button type="button" class="navbar-toggler hamburger hamburger-close navbar-toggler-left hided"
  data-toggle="menubar">
  <span class="sr-only">Toggle navigation</span>
  <span class="hamburger-bar"></span>
</button>

<div class="navbar-brand navbar-brand-center site-gridmenu-toggle" data-toggle="gridmenu">
  <span class="navbar-brand-text hidden-xs-down"><%= site_name %></span>
</div>


</div>
<div class="navbar-container container-fluid">
  <!-- Navbar Collapse -->
  <div class="collapse navbar-collapse navbar-collapse-toolbar" id="site-navbar-collapse">
    <!-- Navbar Toolbar -->
    <ul class="nav navbar-toolbar">
      <li class="nav-item hidden-float" id="toggleMenubar">
        <a class="nav-link" data-toggle="menubar" href="#" role="button">
          <i class="icon hamburger hamburger-arrow-left">
            <span class="sr-only">Toggle menubar</span>
            <span class="hamburger-bar"></span>
          </i>
        </a>
      </li>


      <li class="nav-item dropdown dropdown-fw dropdown-mega">
          <%= render 'header_trending' %>
    </li>
  </ul>
  <!-- End Navbar Toolbar -->
  <!-- Navbar Toolbar Right -->
  <ul class="nav navbar-toolbar navbar-right navbar-toolbar-right">
    <li class="nav-item ">
      <%= link_to sign_in_path, class: "nav-link" do %>
        Sign in
      <% end %>
    </li>
    <li class="nav-item ">
      <%= link_to new_user_path, class: "nav-link" do %>
        Sign up
      <% end %>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="javascript:void(0)" data-animation="scale-up"
      aria-expanded="false" role="button">
      <span class="flag-icon flag-icon-us"></span>
    </a>
    <div class="dropdown-menu" role="menu">
      <a class="dropdown-item" href="javascript:void(0)" role="menuitem">
        <span class="flag-icon flag-icon-us"></span> English</a>
        <a class="dropdown-item" href="javascript:void(0)" role="menuitem">
          <span class="flag-icon flag-icon-br"></span> Portuguese</a>



        </div>
      </li>





</ul>
<!-- End Navbar Toolbar Right -->
<div class="navbar-brand navbar-brand-center">
  <%= link_to projects_path do %>
  <%= image_tag "flosscoach", height: "30" %>
  <% end %>
</div>
</div>
<!-- End Navbar Collapse -->

</div>
</nav>

app/views/visitor/_menu.html.erb
<div class="site-menubar">
  <div class="site-menubar-body">
    <div>
      <div>
        <ul class="site-menu" data-plugin="menu">
          <li class="site-menu-item has-sub">
            <a href="javascript:void(0)">
              <i class="site-menu-icon md-view-compact" aria-hidden="true"></i>
              <span class="site-menu-title">Projects</span>
              <span class="site-menu-arrow"></span>
            </a>
            <ul class="site-menu-sub">
              <li class="site-menu-item">
                <%= link_to projects_path do %>
                <span class="site-menu-title">All projects</span>
                <% end %>
              </li>
              <li class="site-menu-item">
                <%= link_to recent_projects_path do %>
                <span class="site-menu-title">Recent projets</span>
                <% end %>
              </li>
              <li class="site-menu-item">
                <%= link_to most_favorited_projects_path do %>
                <span class="site-menu-title">Most favorited</span>
                <% end %>
              </li>
            </ul>
          </li>
        </ul>
      </li>



    </ul>
  </li>
</ul>
</div>
</div>
</div>
</div>