config/routes.rb
Rails.application.routes.draw do


  root :to => "presentation_page#index"
  resources :password_resets
  get 'open_hub/similar', :to => "projects#similiar_open_hub_projects"

  resources :projects do
    get 'most_favorited', on: :collection
    get 'recent', on: :collection
    resources :ownership_requests, :controller => "projects/ownership_requests"
    resources :comments, :controller => "projects/comments"

    resources :users, :controller => "projects/users"
    post :favorite, :to =>"projects/favorites#create"
    delete :favorite, :to =>"projects/favorites#destroy"
    
    resources :widgets do
      resources :comments, :controller => "widgets/comments"
=begin 
        collection do
          put :approve
        end
=end
    end
  end

  #Comment Moderation:
  get '/projects/:project_id/widgets/:widget_id/moderate(.:format)', to: 'widgets/comments#moderate', as: 'moderate'
  put '/projects/:project_id/widgets/:widget_id/comments', to: 'widgets/comments#approve', as: 'approve_comments'
  #resources :widgets
  resources :forums do
    #this is for passing the project_id to the forum that's being created
    resources :topics do
      resources :messages
    end
  end
  
  put 'forums/new/:project_id' => 'forums#create', as: 'create_forum'
  resources :widget_comments, :controller => "widgets/comments"
  resources :project_comments, :controller => "projects/comments", only: [:create]
  resources :sessions

  # Oauth Related code
	get 'auth/:provider/callback', to: 'omni_auth_login#create'
  get 'auth/failure', to: redirect('/')
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  delete 'signout' => 'sessions#destroy'

  #Favoriting project related code:
  post "/users/favorite_project/:project_id" => "users#favorite_project"
  post "/users/disfavorite_project/:project_id" => "users#disfavorite_project"

  resources :users do
    member do
      get :confirm_email
    end
  end

  #tabs related code:
  get '/projects/:id/start',     to: 'projects#start',     as: 'start'
  get '/projects/:id/community', to: 'projects#community', as: 'community'
  get '/projects/:id/workspace', to: 'projects#workspace', as: 'workspace'
  get '/projects/:id/code',      to: 'projects#code',      as: 'code'
  get '/projects/:id/changes',   to: 'projects#changes',   as: 'changes'
  get '/projects/:id/success_stories',   to: 'projects#success_stories',   as: 'success_stories'
  
end

app/models/topic.rb
class Topic < ApplicationRecord
  include Taggable

  belongs_to :forum
  has_many :messages, :dependent => :destroy

  belongs_to :user
  validates_presence_of :forum
  validates_presence_of :user

  def project
    forum.project
  end

  def messages_count
    messages.count
  end

  def recent?
    created_at > 2.day.ago
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :set_forum_and_project
  before_action :authorize, except: [:show]


  # GET /topics
  def index
    @topics = @project.topics
  end

  # GET /topics/1
  def show

  end


  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  def create
    @topic = Topic.new(topic_params)
    @topic.forum = @forum
    @topic.user = current_user
    if @topic.save
      redirect_to forum_path(@forum.project_id), success: 'Topic was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /topics/1
  def update
    if @topic.update(topic_params)
      
      redirect_to [@topic.forum,@topic], notice: 'Topic was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /topics/1
  def destroy
    @topic.destroy
    redirect_to @forum, notice: 'Topic was successfully destroyed.'
  end

    
  private
    # Use callbacks to share common setup or constraints between actions.
    #now is set propely
    def set_forum_and_project
      @forum = Forum.find(params[:forum_id])
      @project = @forum.project
    end

    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def topic_params
      params.require(:topic).permit!
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for [@forum, topic] do |f| %>
  <% if topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topic.errors.count, "error") %> must be fixed in order to save this topic:</h2>

      <ul>
      <% topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-lg-12 form-group">
      <%= f.label :title %>
      <%= f.text_field :title , :class => "form-control", placeholder: "Topic title" %>
    </div>

    <div class="col-lg-12 form-group">
      <%= f.label :content %>

      <%= f.text_area :content, :class => "form-control", placeholder: "Content" %>
    </div>
</div>
<div class="row">

  <div class="col-lg-12 form-group">
    <%= f.submit "Create topic", class:"btn btn-primary"%>
  </div>
</div>

<% end %>

app/views/topics/_topic.html.erb
<tr data-href="<%= forum_topic_url(@forum, topic) %>" data-toggle="slidePanel">
  <td class="pre-cell"></td>
  <td class="cell-60 responsive-hide">
    <a class="avatar" href="javascript:void(0)">
      <%= image_tag topic.user.avatar.url(:thumb), class: "img-fluid" %>
    </a>
  </td>
  <td>
    <div class="content">
      <div class="title">
        <%= topic.title %>
        <div class="flags responsive-hide">
          <% if false %>
          <span class="sticky-top badge badge-round badge-danger">
            <i class="icon md-caret-up-circle" aria-hidden="true"></i>
            TOP</span>

            <% end %>
          <% if topic.locked?%>
          <i class="locked icon md-lock"></i>
          <% end %>
        </div>
      </div>
      <div class="metas">
        <span class="author"><%= topic.user.name %></span>
        <span class="started"><%=topic.created_at.strftime("%b %d, %Y | %H:%M")%></span>
      </div>
    </div>
  </td>
  <td class="cell-80 forum-posts">
    <span class="num"><%= topic.messages_count %></span>
    <span class="unit">Post</span>
  </td>
  <td class="suf-cell"></td>
</tr>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form', topic: @topic %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Topics</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= link_to 'Show', topic %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<div class="page-content">
  <div class="panel panel-bordered">
    <div class="panel-heading">
      <h3 class="panel-title">New Topic on <%= @project.name %> forum</h3>
        </div>
          <div class="panel-body">
            <%= render 'form', topic: @topic %>
          </div>
        <div class="panel-footer"> 
      <%= link_to "Back to #{@project.name} forum", forum_path(@forum.project_id), class:"btn btn-danger" %>
    </div>
  </div>
</div>

app/views/topics/show.html.erb
<%= render 'visitor/header' unless current_user %>
<%= render 'visitor/menu' unless current_user %>
<div class="page-header">

</div>

<div class="page-content">

  <div class="panel panel-bordered">
    <div class="panel-heading">
      <h3 class="panel-title"><%= @topic.title %></h3>
    </div>
    <div class="panel-body">
      <div class="testimonial testimonial-top">
                    <ul class="testimonial-ul row">
                      <li class="testimonial-item col-sm-12">
                        <div class="testimonial-image">
                          <%= link_to @topic.user, class: "avatar" do %>
                            <%= image_tag @topic.user.photo_url %>
                          <% end %>
                        </div>
                        <span class="testimonial-author">@<%= link_to @topic.user.username, @topic.user%></span>
                        <span class="testimonial-company"></span>
                        <div class="testimonial-content">
                          <p><%= @topic.content %></p>
                        </div>
                      </li>
                    </ul>
                  </div>
    </div>
    <div class="panel-footer">
      <%= link_to 'Add answer', new_forum_topic_message_path(@topic.forum, @topic), class:"btn btn-primary" %>
      
      <%if @project.owners.ids.include?(current_user.id)%>
      <%=link_to "Edit this topic", edit_forum_topic_path(), class:"btn btn-warning" %>
      <%= link_to "Delete this topic",  forum_topic_path(),method: :delete, data: { confirm: "Are you completely sure? This can't be undone!" }, class:"btn btn-danger" %>
      <%end%>
    </div>
  </div>


  <div class="panel">
    <div class="panel-body">
      <div class="comments mx-20">
        <h3>Answers for topic <b><%= @topic.title %></b></h3>

        <% @topic.messages.each do |message| %>


        <div class="comment media">
          <div class="pr-15">
            <%= link_to message.user, class: "avatar avatar-md" do %>
            <%= image_tag message.user.photo_url %>
            <% end %>
          </div>
          <div class="comment-body media-body">
            <div class="comment-title">
              <div class="comment-meta float-right">
                <span><%=message.created_at.strftime("%b %d, %Y | %H:%M")%></span>
              </div>
              <%= link_to message.user.name ,message.user, class: "comment-author"%>
            </div>
            <div class="float-right">
              <!-- link_to 'Edit message ', edit_forum_topic_message_path(@topic.forum, @topic) -->
            </div>
            <%if message.user_id == current_user.id%>
              <div class="float-right">
                <%= link_to 'Delete message',  forum_topic_message_path(topic_id: message.topic_id, message_id: message.id),  method: :delete, data: { confirm: "Are you sure? This can't be undone" } %>
              </div>
            <%end%>
            <div class="comment-content">
              <p><%= message.content %></p>
            </div>
          </div>
        </div>
        <%end%>
      </div>
    </div>
  </div>
<%=link_to "Back to #{@project.name} forum", forum_path(@project.id), class:"float-right"%> 
</div>