config/routes.rb
Rails.application.routes.draw do


  root :to => "presentation_page#index"
  resources :password_resets
  get 'open_hub/similar', :to => "projects#similiar_open_hub_projects"

  resources :projects do
    get 'most_favorited', on: :collection
    get 'recent', on: :collection
    resources :ownership_requests, :controller => "projects/ownership_requests"
    resources :comments, :controller => "projects/comments"

    resources :users, :controller => "projects/users"
    post :favorite, :to =>"projects/favorites#create"
    delete :favorite, :to =>"projects/favorites#destroy"
    
    resources :widgets do
      resources :comments, :controller => "widgets/comments"
=begin 
        collection do
          put :approve
        end
=end
    end
  end

  #Comment Moderation:
  get '/projects/:project_id/widgets/:widget_id/moderate(.:format)', to: 'widgets/comments#moderate', as: 'moderate'
  put '/projects/:project_id/widgets/:widget_id/comments', to: 'widgets/comments#approve', as: 'approve_comments'
  #resources :widgets
  resources :forums do
    #this is for passing the project_id to the forum that's being created
    resources :topics do
      resources :messages
    end
  end
  
  put 'forums/new/:project_id' => 'forums#create', as: 'create_forum'
  resources :widget_comments, :controller => "widgets/comments"
  resources :project_comments, :controller => "projects/comments", only: [:create]
  resources :sessions

  # Oauth Related code
	get 'auth/:provider/callback', to: 'omni_auth_login#create'
  get 'auth/failure', to: redirect('/')
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  delete 'signout' => 'sessions#destroy'

  #Favoriting project related code:
  post "/users/favorite_project/:project_id" => "users#favorite_project"
  post "/users/disfavorite_project/:project_id" => "users#disfavorite_project"

  resources :users do
    member do
      get :confirm_email
    end
  end

  #tabs related code:
  get '/projects/:id/start',     to: 'projects#start',     as: 'start'
  get '/projects/:id/community', to: 'projects#community', as: 'community'
  get '/projects/:id/workspace', to: 'projects#workspace', as: 'workspace'
  get '/projects/:id/code',      to: 'projects#code',      as: 'code'
  get '/projects/:id/changes',   to: 'projects#changes',   as: 'changes'
  get '/projects/:id/success_stories',   to: 'projects#success_stories',   as: 'success_stories'
  
end

app/models/widgets/default_widget.rb
class DefaultWidget < Widget
  def to_partial_path
     'widgets/widget'
   end

end

app/models/widgets/opinion_widget.rb
class OpinionWidget < Widget
  before_create :define_slug

  def self.generate
    OpinionWidget.build("Opinion by the others newcomes", tab: :about, x: 0, y: 11, width: 12, height: 5)
  end
  def content
    ApplicationController.render 'widgets/opinion_widget', layout: false,assigns:{ project: project }
  end

  def to_partial_path
     'widgets/widget'
   end

   private
   def define_slug
     self.slug = 'opinion_widget'
   end
end

app/models/widgets/widget.rb
class Widget < ApplicationRecord
  after_initialize :set_defaults, unless: :persisted?

  validates_presence_of :title
  validates_presence_of :tab #tab-slug?
  validates_presence_of :pos_x
  validates_presence_of :pos_y
  validates_presence_of :width
  validates_presence_of :height

  belongs_to :project
  scope :from_tab, -> (tab) {where("tab= ?", tab.to_s)}

  has_many :comments, :dependent => :destroy
  before_create :create_slug

  before_create :set_defaults
  def self.generate_all
    widgets = DefaultWidget.generate_all
    widgets << OpinionWidget.generate
    widgets
  end


  def tip
    DefaultTip.where(widget_slug: slug) if default?
  end

  def tip?
    !tip.empty?
  end

  def default?
    is_a?(DefaultWidget)
  end

  

  private

  def set_defaults
    self.resizeable ||=  true
    self.retractable ||= false
  end

  def create_slug
    self.slug ||= self.title.parameterize
  end

  def to_partial_path
     'widgets/widget'
   end
end

app/models/widgets/widget_factory.rb
class WidgetFactory
  TYPES = {
    default_widget: DefaultWidget,
    opinion_widget: OpinionWidget
  }
  def self.for(type, open_hub_data: nil )
    factory = WidgetFactory.new
    factory.for(type, open_hub_data: open_hub_data)
  end

  def for(type, open_hub_data: nil)
    if type == :default_widgets
      build_default_widgets(open_hub_data: open_hub_data)
    else
      #TODO: build_widget(type, attributes)
    end
  end

  def build_default_widgets(open_hub_data: nil)
    widgets = []
    content = open_hub_data.iframe_html if open_hub_data
    widgets << self.build_widget(:default_widget, "About the project", tab: :about, x: 0, y: 0, width: 6, height: 5, content: content)

    content = open_hub_data.iframe_languages_html if open_hub_data
    widgets << self.build_widget(:default_widget,"Technical skills required", tab: :about, x: 6, y: 0, width: 6, height: 5, content: content )

    content = open_hub_data.links_html if open_hub_data
    widgets << self.build_widget(:default_widget,"Resources avaiable", tab: :about, x: 0, y: 5, width: 6, height: 5, content: content)
    widgets << self.build_widget(:default_widget,"Soft skills required", tab: :about, x: 6, y: 5, width: 6, height: 5)
    widgets << self.build_widget(:default_widget,"Easy tasks", tab: :choosing_a_task_to_start_with, x: 0, y: 0, width: 12, height: 5)


    widgets << self.build_widget(:default_widget,"Finding Mentorship and Support", tab: :find_a_mentor, x: 0, y: 0, width: 12, height: 5)

    widgets << self.build_widget(:default_widget,"Searching the mailing list", tab: :search_before_ask, x: 0, y: 0, width: 6, height: 4)
    widgets << self.build_widget(:default_widget,"Search project site", tab: :search_before_ask, x: 6, y: 0, width: 6, height: 4)

    widgets << self.build_widget(:default_widget,"Synchronous help", tab: :synchronous_chat, x: 0, y: 0, width: 12, height: 4)

    widgets << self.build_widget(:default_widget,"Subscribing to mailing list", tab: :mailing_lists, x: 0, y: 0, width: 6, height: 4)
    widgets << self.build_widget(:default_widget,"Information about mailing list", tab: :mailing_lists, x: 6, y: 0, width: 6, height: 4)

    widgets << self.build_widget(:default_widget,"Resources provided by the project", tab: :setup_your_workspace, x: 0, y: 0, width: 6, height: 4)
    widgets << self.build_widget(:default_widget,"Search for solutions in the mailing list", tab: :setup_your_workspace, x: 6, y: 0, width: 6, height: 4)

    widgets << self.build_widget(:default_widget,"Code documentation", tab: :deal_with_the_code, x: 0, y: 0, width: 6, height: 4)
    widgets << self.build_widget(:default_widget,"Searchable resources", tab: :deal_with_the_code, x: 6, y: 0, width: 6, height: 4)

    widgets << self.build_widget(:default_widget,"Submitting your contribution", tab: :submit_your_changes, x: 0, y: 0, width: 12, height: 4)
    widgets << self.build_widget(:opinion_widget, "Opinion by the others newcomes", tab: :about, x: 0, y: 11, width: 12, height: 5, editable: false, deletable: false)

    widgets << self.build_widget(:default_widget,"Success stories on this project", tab: :success_stories, x: 0, y: 0, width: 12, height: 4)
    widgets
  end

  def build_widget(type, title, slug: nil , tab:, x:, y:, width:, height:, editable: true, deletable: false, content: nil)
    widget = (TYPES[type] || DefaultWidget).new
    widget.title = title
    widget.slug = slug || title.parameterize
    widget.tab = tab
    widget.pos_x = x
    widget.pos_y = y
    widget.width = width
    widget.height = height
    widget.content = content
    widget.deletable = deletable
    widget.editable = editable
    widget
  end





end

app/controllers/widgets/comments_controller.rb
class Widgets::CommentsController < WidgetsController
  before_action :set_comment, only: [:show, :update, :destroy]
  before_action :set_widget, only: [:show, :update, :create]
  before_action :set_project, only: [:approve, :owner, :create]
  skip_before_filter :verify_authenticity_token, only: [:update]
  before_action :authorize

  # GET /users
  def index
    if params[:without_replies]
      @comments = @widget.comments.is_not_replies
    else
      @comments = @widget.comments
    end
  end

  # GET /users/1
  def show
    redirect_to comment.widget.project
  end

  # POST /users
  def create
    @comment = WidgetComment.new(comment_params)
    @comment.user = current_user
    @comment.widget = @widget
    @widget.comments << @comment
    @comment.project_id = @widget.project.id
    @comment.status = "draft"

    if comment_params[:reply_to_id]
      comment_dad = WidgetComment.find(comment_params[:reply_to_id])
      comment_dad.replies << @comment
    end

    if @project.owners.include?(current_user)
      @comment.status = "approved"
    end
    
    respond_to do |format|
    if @comment.save
      flash.now[:notice] = "Comment was successfully saved."
        format.js
        format.html
      end
    end
  end

  # PATCH/PUT /users/1
  def update
    if @widget.update_attributes(widget_params)
      respond_to do |format|
        format.json { render :json => { :status => 'Ok', :message => 'Received'}, :status => 200 }
      end
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
     id = @comment.project_id 
    @comment.destroy
    redirect_to project_path(id), notice: 'Comment was successfully destroyed.'
  end


  def approve
    ids = params[:comment_ids]
    ids.each do |id|
      c = WidgetComment.find(id)
      c.status = "approved"
      c.save
    end
   redirect_to @project
  end


  def moderate
    @widget = set_widget
    render 'moderate'
  end

  private
  # Only allow a trusted parameter "white list" through.
  def comment_params
    params.require(:widget_comment).permit!
  end

  def set_comment
    @comment = WidgetComment.find(params[:id])
  end
  def set_widget
    @widget = Widget.find(params[:widget_id])
  end

  def set_project
    @project = Widget.find(params[:widget_id]).project
  end

end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  before_action :set_widget, only: [:show, :update, :destroy, :edit, :good_first_issues]
  before_action :tips, only: [:show]
  skip_before_filter :verify_authenticity_token, only: [:update]

  def index
    @widgets = @project.widgets    
  end

  def show
    redirect_to @widget.project
  end

  def create
    @widget = Widget.new(widget_params)
    @project = @widget.project
    @widget.closeable = true
    if @widget.save
        #format.json { render :json => { :status => 'Ok', :message => 'Received'}, :status => 200 }
        redirect_to @project
    else
      flash.now[:notice] = @widget.errors.full_messages
      redirect_to @project
    end
  end
  def edit

  end
  def update
    if @widget.update_attributes(widget_params)
      respond_to do |format|
        format.json { render :json => { :status => 'Ok', :message => 'Received'}, :status => 200 }
        format.html { redirect_to @project }
      end
    else
      render :edit
    end
  end

  def destroy
    @widget.destroy
    redirect_to @project, success: 'Widget was successfully destroyed.'
  end

  def owner(current_user)
    if @project.owner?(current_user)
      return true
    end
    return false
  end
  helper_method :owner

  

  private
  # Only allow a trusted parameter "white list" through.
  def widget_params
    params.require(:widget).permit!
  end

  def set_widget
    @widget = Widget.all.find(params[:id])
    @project = @widget.project
  end
  
end

app/views/widgets/_opine_form.html.erb
<%= form_for ProjectComment.new , remote: true do |f| %>
<div class="form-group">

  <h4>Content</h4>

  <%= f.text_area :content, class: "form-control" %>
  <%= hidden_field_tag :project_id ,@project.id %>
</div>

    <div class="form-group">
      <%= f.submit "Comment", class: "btn btn-primary" %>
    </div>

<% end %>

app/views/widgets/_widget.erb
<div class="grid-stack-item"
    data-gs-id="<%= widget.id %>"
    data-gs-x="<%= widget.pos_x %>"
    data-gs-y="<%= widget.pos_y %>"
    data-gs-width="<%= widget.width %>"
    data-gs-height="<%= widget.height %>"
    data-gs-slug="<%= widget.slug %>"
    data-gs-no-resize="<%= 'true' unless @project.owner?(current_user)  %>"
    data-gs-no-move="<%= 'true' unless @project.owner?(current_user)  %>"
    data-gs-locked="<%= 'true' unless @project.owner?(current_user)  %>">

  <div class="grid-stack-item-content panel panel-bordered panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title"><%= widget.title %></h3>

      <div class="panel-actions">
        <% if logged_in? %>
        <a class="panel-action icon wb-chat-group" data-target='#comments<%= widget.id %>' data-toggle="modal"></a>
        <% end %>

        <% if @project.owner?(current_user) && widget.editable?   %>
        <%= link_to "", edit_project_widget_path(@project,widget), class: "panel-action icon wb-edit "%>
        <%= link_to "", moderate_path(@project,widget), class: "panel-action icon  wb-stats-bars"%>
        <% end %>

        <a class="panel-action icon fa-bolt" href="javascript:void(0)"
        data-plugin="webuiPopover" data-title="What to fill this box:"
        data-content="<p><%=tips(widget)%></p>"
        data-target="webuiPopover3"></a>

        <% if logged_in? && widget.deletable? && @project.owner?(current_user) %>
        <%= link_to "", project_widget_path(@project, widget),
        method: :delete, :class => "panel-action icon wb-close",
        :data => {confirm: "Are you sure in deleting this widget?", toogle: 'panel-close'} %>
        <% end %>
      </div>

    </div>
    <div class="panel-body" id="<%= widget.id %>">
      <%= widget.content.html_safe if widget.content %>
    </div>
  </div>
</div>

<% create_modal("Comments", "comments#{widget.id}") do %>
    <div class="comments">
      <%= render widget.comments.except_replies %>
    </div>
    <%= render 'widgets/comments/form', :widget => widget %>
<% end if widget.commentable? %>


<% create_modal("Opine here!", "project_comments") do %>
    <%= render "projects/comments/form" %>
<% end if widget.is_a?(OpinionWidget) %>

app/views/widgets/edit.html.erb
<div class="page-header">
  <h1 class="page-title ">Editing Widget "<%= @widget.title %>" of project <%= @project.name %></h1>
  <p class="lead">
    Add your project to <%= site_name %> and help newbies collaborate with your project.
  </p>
</div>

<div class="page-content">

  <div class="panel">
    <div class="panel-body">

      <%= simple_form_for [@project,@widget.becomes(Widget)] do |f| %>
        <%= f.input :title unless @widget.default?%>
        <%= f.input :content, as: :summernote %>
        <%= f.button :submit, data: { disable_with: "Updating widget..." }%>
      <% end %>
  </div>

  </div>

</div>

app/views/widgets/opinion_widget.html.erb
<div class="all_project_comments">
<%= render @project.comments.except_replies %>
</div>
<p>
<button data-target='#project_comments' data-toggle="modal">
Comment on <%= @project.name %> project
</button>
</p>