config/routes.rb
Rails.application.routes.draw do


  root :to => "presentation_page#index"
  resources :password_resets
  get 'open_hub/similar', :to => "projects#similiar_open_hub_projects"

  resources :projects do
    get 'most_favorited', on: :collection
    get 'recent', on: :collection
    resources :ownership_requests, :controller => "projects/ownership_requests"
    resources :comments, :controller => "projects/comments"

    resources :users, :controller => "projects/users"
    post :favorite, :to =>"projects/favorites#create"
    delete :favorite, :to =>"projects/favorites#destroy"
    
    resources :widgets do
      resources :comments, :controller => "widgets/comments"
=begin 
        collection do
          put :approve
        end
=end
    end
  end

  #Comment Moderation:
  get '/projects/:project_id/widgets/:widget_id/moderate(.:format)', to: 'widgets/comments#moderate', as: 'moderate'
  put '/projects/:project_id/widgets/:widget_id/comments', to: 'widgets/comments#approve', as: 'approve_comments'
  #resources :widgets
  resources :forums do
    #this is for passing the project_id to the forum that's being created
    resources :topics do
      resources :messages
    end
  end
  
  put 'forums/new/:project_id' => 'forums#create', as: 'create_forum'
  resources :widget_comments, :controller => "widgets/comments"
  resources :project_comments, :controller => "projects/comments", only: [:create]
  resources :sessions

  # Oauth Related code
	get 'auth/:provider/callback', to: 'omni_auth_login#create'
  get 'auth/failure', to: redirect('/')
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  delete 'signout' => 'sessions#destroy'

  #Favoriting project related code:
  post "/users/favorite_project/:project_id" => "users#favorite_project"
  post "/users/disfavorite_project/:project_id" => "users#disfavorite_project"

  resources :users do
    member do
      get :confirm_email
    end
  end

  #tabs related code:
  get '/projects/:id/start',     to: 'projects#start',     as: 'start'
  get '/projects/:id/community', to: 'projects#community', as: 'community'
  get '/projects/:id/workspace', to: 'projects#workspace', as: 'workspace'
  get '/projects/:id/code',      to: 'projects#code',      as: 'code'
  get '/projects/:id/changes',   to: 'projects#changes',   as: 'changes'
  get '/projects/:id/success_stories',   to: 'projects#success_stories',   as: 'success_stories'
  
end

app/models/project.rb
class Project < ApplicationRecord
  before_save :normalize_blank_values

  mount_uploader :avatar, AvatarUploader
  include Taggable

  #Validations:
  validates_presence_of :name
  validates_uniqueness_of :name, :case_sensitive => false
  validates_presence_of :description, unless: :open_hub_id
  validates :avatar, file_size: { less_than: 3.megabytes }
  validates :repo_info, :format => {
  :with => /\w+\/\w+/,
  :message => "is not valid, please insert a valid repository info",
  :if => lambda{ |object| object.repo_info.present? } 
  }

  #Associations:
  belongs_to :user
  has_many :widgets, :dependent => :destroy
  has_and_belongs_to_many :owners, class_name: 'User'
  has_one :forum, :dependent => :destroy
  has_many :favoriter_projects
  has_many :fans, through: :favoriter_projects, :source => :user
  has_many :comments, class_name: 'ProjectComment'

  has_many :ownership_requests, :dependent => :destroy
  has_many :pendent_ownership_requests, -> { pendent }, :class_name => 'OwnershipRequest'
  has_many :pendent_owners, :source => :user, through: :pendent_ownership_requests

  #Status related code:
  scope :active, -> { where status: 'active'}
  scope :inactive, -> { where status: 'inactive'}

  before_create :transform_tags
  before_create :get_open_hub_data, if: :open_hub_id

  before_create :create_widgets
  #before_save :update_image_attributes

  attr_accessor :plain_tags
  def image
    avatar
  end

  def normalize_blank_values
    attributes.each do |column, value|
      self[column].present? || self[column] = nil
    end
  end


  def image_url
    avatar.url
  end


  def get_open_hub_data
    @open_hub_project = OpenHubProject.find_by_name(self.name)
    self.open_hub_id = @open_hub_project.id
    puts(self.open_hub_id)
    ohp = open_hub_project
    self.description = ohp.description
    self.remote_avatar_url = ohp.logo_url
    ohp.tags.each {|tag| self.tags << Tag.from_string(tag)}
    self.open_hub_id = ohp.id
  end


  def open_hub_project
    @open_hub_project ||= OpenHubProject.find_by_id(self.open_hub_id) if self.open_hub_id
    @open_hub_project
  end

  def recent?
    created_at > 2.day.ago
  end

  def dismiss_request_ownership(user)
    pendent_owners.delete(user)
  end
  def photo_url
    if use_open_hub_image
      open_hub_image_url  || "/assets/no-image.png"
    elsif !avatar.url.nil?
      avatar.url
    else
      "/assets/no-image.png"
    end
  end

  def photo_url_uploaded
      avatar.url
  end
  def pendent_ownership_requests
    ownership_requests.where(approved:nil)
  end
  def owner?(user)
    self.owners.include?(user)
  end
  
  def add_owner(user)
    owners << user unless owner?(user)

  end
  def remove_owner(user)
    owners.delete(user) if owner?(user)
  end

  def self.search(search)
    if search
      query = "projects.name LIKE ? OR projects.description LIKE ? OR tags.name LIKE ?"
      results = includes(:tags).where(query, "%#{search}%","%#{search}%", "%#{search}%").references(:tags)
    else
      results = all
    end
    results.distinct
  end

  private
  def transform_tags
    if self.plain_tags
      self.tags << Tag.array_to_tags(plain_tags.split(","))
    end
  end

  def create_widgets
    self.widgets << WidgetFactory.for(:default_widgets, open_hub_data: open_hub_project)
  end
=begin
  def update_image_attributes
    if image.present?
      self.image_content_type = image.file.content_type 
      self.image_file_size = image.file.size
    end

  end
=end

end

app/controllers/projects/comments_controller.rb
class Projects::CommentsController < ProjectsController
  before_action :set_comment, only: [:show, :update, :destroy]
  before_action :set_project, only: [:show, :update, :destroy, :create]
  skip_before_filter :verify_authenticity_token, only: [:update]
  before_action :authorize
  # GET /users
  def index

  end

  # GET /users/1
  def show
    redirect_to comment.widget.project
  end

  # POST /users
  def create
    @comment = ProjectComment.new(comment_params)
    @comment.user = current_user
    @comment.project = @project
    @project.comments << @comment
    if comment_params[:reply_to_id]
      comment_dad = ProjectComment.find(comment_params[:reply_to_id])
      comment_dad.replies << @comment
    end

    respond_to do |format|
      if @comment.save
        flash.now[:notice] = "Comment was successfully saved."
        format.js
        format.html

      end
    end
  end

  # PATCH/PUT /users/1
  def update
    if @comment.update_attributes(comment_params)
      respond_to do |format|
        format.json { render :json => { :status => 'Ok', :message => 'Received'}, :status => 200 }
      end
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @comment.destroy
    redirect_to @project, notice: 'Widget?(comment) was successfully destroyed.'
  end


  private
  # Only allow a trusted parameter "white list" through.
  def comment_params
    params.require(:comment).permit!
  end

  def set_comment
    @comment = ProjectComment.find(params[:id])
  end
  def set_project
    @project = Project.find(params[:project_id])
  end
end

app/controllers/projects/favorites_controller.rb
class Projects::FavoritesController < ProjectsController

  before_action :set_user
  before_action :set_project

  # POST /users
  def create
    @projects = Project.all
    project = Project.find_by_id(params[:project_id])
    respond_to do |format|
      @user.favorite_project(project)
      if @user.save
        format.js
        format.html{
          flash.now[:notice] = "Project #{@project.name} has been favorited!."
          redirect_to project_path(@project)
        }
      else
        format.js
        format.html{
          flash.now[:notice] = "Erron on favorite project #{@project.name}."
          redirect_to project_path(@project)
        }
      end
    end
  end

  # DELETE /users/1
  def destroy
    @projects = Project.all

    respond_to do |format|
      if @user.favorited_projects.delete(@project)
        format.js
        format.html{
          flash.now[:notice] = "Project #{@project.name} has been disfavorited!."
          redirect_to project_path(@project)
        }
      else
        format.js
        format.html{
          flash.now[:notice] = "Erron on disfavorite project #{@project.name}."
          redirect_to project_path(@project)
        }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = current_user
  end

  def set_project
    @project = Project.find(params[:project_id])
  end

end

app/controllers/projects/ownership_requests_controller.rb
class Projects::OwnershipRequestsController < ProjectsController

  before_action :set_ownership_request, only: [:show, :edit, :update, :destroy]
  before_action :set_project
  # POST /ownership_requests
  def create
    current_user.request_ownership(@project)
    respond_to do |format|
       format.js #this will call delete.js.erb when js action is called
     end
  end

  def update
    if @approved == true
      @ownership_request.approve
    else
      @ownership_request.disapprove
    end

    respond_to do |format|
       format.js #this will call delete.js.erb when js action is called
     end
  end

  #cancel ownership
  def destroy
    @project.dismiss_request_ownership(current_user)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ownership_request
      @ownership_request = OwnershipRequest.find(params[:id])
      @approved = (params[:approved] == "true") # 3 fuckin hours to discovery this
    end

    # Only allow a trusted parameter "white list" through.

    def set_project
      @project = Project.find(params[:project_id])
    end

end

app/controllers/projects/users_controller.rb
class Projects::UsersController < ProjectsController

  before_action :set_project, only: [:index, :destroy, :new, :create]
  before_action :set_user, only: [:show, :update, :destroy]

  skip_before_filter :verify_authenticity_token, only: [:update]
  before_action :authorize

  # GET /users
  def index
    @project = Project.all.find(params[:project_id])
  end

  # GET /users/new
  def new
  end

  # POST /users
  def create
    @user = User.find_by_email(params[:email])
    if @user
      @project.owners << @user
      redirect_to project_users_path, success: "#{@user.username} is a owner now."
    else
      flash.now[:error] = "No user matches with this e-mail."
      render :new
    end
  end

  # DELETE /users/1
  def destroy
    if current_user == @user && @project.owners.count == 1
      redirect_to project_users_path, error: 'You cannot delete yourself because you are the unique owner of this project.'
    else
      if @project.owners.delete(@user)
        redirect_to project_users_path, notice: 'Done.'
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = @project.owners.find_by_slug(params[:id])
  end

  def set_project
    @project = Project.find(params[:project_id])
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, except: [:new, :create, :similiar_open_hub_projects,
                                        :recent, :most_favorited]
  respond_to :html, :js, :json
  skip_before_action :verify_authenticity_token, only: [:update]

  before_action :authorize, except: [:index, :show, :start, :community,
                                     :workspace, :code, :changes,:recent,
                                     :most_favorited, :success_stories]
  skip_before_action :set_project, only: [:index]
  # GET /projects
  def index
    @projects = Project.search(params[:search])
 	  @project = Project.new
    @order_by ||= "Recents"
  end

  # GET /projects/1
  def show
    github_issues
  end

  #placebo actions for tabs:
  def test
    github_issues
  end
  def start
    github_issues
  end

  def community
    github_issues
  end

  def workspace
    github_issues
  end

  def code
    github_issues
  end

  def changes
    github_issues
  end

  def success_stories
    github_issues
  end
  
  #end of actions for tabs




  # GET /projects/new
  def new
    @project = Project.new
  end
  
  def recent
    @projects = Project.active.search(params[:search])
    @project = Project.new
    @order_by = "Recents"

    render :index
  end

  def most_favorited
    @projects = Project.active.search(params[:search])
    @project = Project.new
    @order_by ||= "Most favorited"

    render :index

  end
  # GET /projects/1/edit
  def edit
    unless @project.owner?(current_user)
      render :show, status: :unauthorized, error: 'Access unauthorized'
    end
    @codigourl = params[:id]
  end

  #TODO: Refactor and create a Open Hub Controller
  def similiar_open_hub_projects
    projects = OpenHubProject.find_by_name(params[:project_name], list:true)
    if projects.empty?
      render json: nil, status: :unprocessable_entity
    else
      render json: OpenHubProject.find_by_name(params[:project_name], list:true), status: :ok
    end
  end

  # POST /projects
  def create
    @project = Project.new(project_params)
    @project.owners << current_user
    @project.primary_owner = current_user.id
    @project.status = "active"
    if @project.save
      redirect_to @project, success: 'Project was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /projects/1
  # TODO: Refactor
  def update
    if @project.owner?(current_user)
      if @project.update_attributes(project_params)
        redirect_to @project, notice: "You edited your project with success!"
      
      else
        respond_to do |format|
          format.html { render :edit, status: :unprocessable_entity, error: 'Update failed!'}
          format.json { render :json => { :status => 'Error', :message => 'Error on update'}, :status => :unprocessable_entity }
        end
      end
    else
      render :show, status: :unauthorized, error: 'Access unauthorized!'
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy
    redirect_to projects_url, success: 'Project was successfully destroyed.'
  end


  #accessing github API, and requesting issues of a project:
  def github_issues
    search_param = @project.repo_info
    if !search_param.blank?
      # Provide authentication credentials:
      client = Octokit::Client.new(:access_token => "957b5755c2b1b73b04cff90093c9e2791fb7fb58", per_page: 20)   
      #search for issues in repo passed as argument:
      response = Octokit.list_issues(search_param,{'labels' => "good first issue" })
      
      issues = [[],[]]
      limit = 10
      response.each do |issue|
        break if limit < 1
        issues[0] << issue['title']
        issues[1] << issue['html_url']
        limit -= 1
      end
      @issues = issues[0].zip issues[1]

      if @issues.empty?
        @issues = nil
        return @issues
      else
        return @issues
      end
    end
    return false
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.includes(:widgets).find(params[:id] || params[:project_id])
    end

    # Only allow a trusted parameter "white list" through.


    def project_params
      params.require(:project).permit!
    end
end

app/views/projects/_project.erb
  <tr data-href="<%= project_url(project) %>" data-toggle="slidePanel">
    <td class="pre-cell"></td>
    <td class="cell-60 responsive-hide">
        <%= link_to project, class: "avatar" do %>
        <% image_tag project.image.url(:thumb), class:"img-fluid" %>
        <% end %>
      </a>
    </td>
    <td>
      <div class="content">
        <div class="title">
          <%= link_to project.name, project %>
        </div>
        <div class="metas">
          <span class="description"><%= project.description %></span>

        </div>
      </div>
    </td>
    <td class="cell-150 forum-posts">

       <div class="rating rating-sm" data-score="4" data-plugin="rating"></div>
    </td>
    <td class="suf-cell"></td>
  </tr>

app/views/projects/_widget_owner.html.erb
<div class="grid-stack-item"
data-gs-x="0"
data-gs-y="0"
data-gs-width="12"
data-gs-height="5"
data-gs-no-resize=""
data-gs-no-move=""
data-gs-locked="">

<div class="grid-stack-item-content panel panel-bordered" >
  <div class="panel-heading">
    <h3 class="panel-title" >Owners</h3>
    <div class="panel-actions">
    </div>
  </div>
  <div class="panel-body">
    <ul class="list-group list-group-full">
      <% @project.owners.each  do |member| %>
      <li class="list-group-item">
        <div class="media">
          <div class="media-left">
            <span class="avatar">
              <%= link_to user_path(member) do %>

              <img class="img-responsive" src="<%= member.avatar.url %>" alt="Photo of <%= member.name %>">
              <% end %>

            </span>
          </div>
          <div class="media-body">
            <%= link_to user_path(member) do %>

            <h4 class="media-heading"><%= member.name %></h4>
            <% end %>

            <small><%= t('Administrator')%></small>

          </div>

          <div class="media-right">
            <%= link_to '' ,project_user_path(@project, member),
            data: {:confirm => t('Are you sure?')}, :class => "status status-lg wb-close" , :method => :delete %>
          </div>
        </div>
      </li>

      <% end %>

    </ul>

    <%= link_to new_project_user_path(@project) do %>
    <button class="btn btn-primary">

      <i class="icon wb-plus" aria-hidden="true"></i>
      Add new administrator
    </button>
    <% end %>

  </div>
</div>
</div>

app/views/projects/index.html.erb
<%= render 'visitor/header' unless current_user %>
<%= render 'visitor/menu' unless current_user %>

<div class="page-header text-center">
  <center>
    <%= image_tag "flosscoach-logo" %>
  </center>
  <h1 class="page-title ">Explore <%= site_name %></h1>
  <p class="lead">
    <%=t('Discover projects, groups and technologies')%> <%=t('Share your projects with others')%>
  </p>
</div>
<!-- Panel -->
<div class="page-content">
  <div class="panel ">
    <div class="panel-heading">
      <h3 class="panel-title"><%= @projects.active.count %> projects found</h3>
    </div>
    <div class="panel-body container-fluid">

      <div class="row row-lg">
        <div class="col-md-8">
          <form class="page-search-form" role="search">
            <div class="form-group">
              <div class="input-group">
                <%= form_tag projects_path, :method => 'get' do %>
                      <%= text_field_tag :search, params[:search], class: "form-control", placeholder:"Search..." %>
                      <span class="input-group-btn">
                      <%= submit_tag raw("Search"), style: "line-height:inherit;",
                      class: "btn btn-primary waves-effect waves-classic", data: { disable_with: "Please wait.." }%>
                    </span>

                  <% end %>


              </div>
              <div class="btn-group">
                <button type="button" class="btn btn-default dropdown-toggle btn-sm" id="searchFilter"
                data-toggle="dropdown" aria-expanded="false">
                Order by: <%= @order_by %>
              </button>
              <div class="dropdown-menu" aria-labelledby="searchFilter" role="menu">
                <%= link_to "Recents", recent_projects_path, class: "dropdown-item" %>
                <%= link_to "Most Favoritered", most_favorited_projects_path, class: "dropdown-item" %>
              </div>
            </div>
          </div>
        </form>


        <div class="page-content  page-content-table  ">
          <table class="table is-indent ">
            <table class="table is-indent">
              <tbody>
                <%= render @projects.active %>
              </tbody>
            </table>
          </div>

        </div>
        <div class="col-md-4">
          <div>
            <h4>Popular tags</h4>
            <div class="list-group list-group-bordered">
              <% Tag.first(10).each do |tag| %>
                <%if tag.projects.active.count >0%>
                  <%= link_to "#{tag} - #{tag.projects.count} results", projects_path(search: tag.to_s), class:"list-group-item" %>
                <%end%>
              <% end %>

            </div>
            <div>
              <% if current_user %>
              <div>
                <%= link_to "Create new project", new_project_path %>
              </div>
              <% end %>
            </div>
          </div>
        </div>

      </div>


    </div>
  </div>

</div>

app/views/projects/show.html.erb
<%if @project.status == "active"%>
  <%= render 'visitor/header' unless current_user %>
  <%= render 'visitor/menu' unless current_user %>

  <div id="<%= @project.id %>" class="page-header page-header-bordered page-header-tabs  nav-tabs-horizontal" data-plugin="tabs">
    <%= render 'notices' %>
    <figure class='logo-projeto text-center'>
      <img class=" img-responsive" src="<%= @project.image_url %>"
      style="max-width:250px;"/>
    </figure>
    <h1 class="page-title text-center"><%= @project.name %>
      </h1>
      <div class="text-center">
          <p>This project is primarily owned by: <%=@project.owners[0].name%></p>
          <% if @project.recent? %>
        <span class="badge badge-danger badge-sm">New</span>
      <% end %>
      </div>
    
    <p class="tags text-center">
      <% @project.tags.each do |tag| %>
        <%= link_to projects_path(search: tag.to_s) do %>
          <span class="badge badge-outline badge-primary"><%=tag.to_s%></span>
        <% end %>
      <% end %>
    </p>


    <p class='text-center'><%= @project.description %></p>
    <div class="text-center">
      <small>Project created <%= time_ago_in_words @project.created_at %> ago</small>
    </div>

    <div class="text-center">    
      <!--  If the user has already created a forum for this project, show it-->
      <%if @project.forum %>
        <%= link_to forum_path(@project.id), class: "btn btn-info waves-effect waves-classic" do %>
          <i class="icon md-comment" aria-hidden="true"></i>Visit the <%= @project.name%> forum!
            <% if @project.recent? %>
              <span class="badge badge-danger badge-sm">New</span>
            <% end %>
        <%end%>
    

    <!--If there isn't forum, create it-->
      <%else%>
        <%= link_to create_forum_path(@project.id), method: :put, class: "btn btn-info waves-effect waves-classic" do %>
        <i class="icon md-comment" aria-hidden="true"></i>Create the <%= @project.name%> forum!
          <% if @project.recent? %>
            <span class="badge badge-danger badge-sm">New</span>
          <% end %>
        <% end %>
      <%end%>
    </div>
      


    <div class="text-center request_ownership_wrapper">
        </br>
        <%= request_ownership_button(@project) %>
    </div>

  </div>
  <!--Projects_show_action header ends here. Body content below:-->


<div class="page-content container-fluid" style="margin: -20px 0px -50px 0px;">
<ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
  
  <li class="nav-item">
    <a class="nav-link active" id="pills-about-tab" data-toggle="pill" href="#pills-about" role="tab">About</a>
  </li>

  <li class="nav-item">
    <%= link_to "How to start", start_path, class:'nav-link'%>
  </li>

  <li class="nav-item">
    <%= link_to ' Talk to the community', community_path, class:'nav-link' %>
  </li>

  <li class="nav-item">
    <%= link_to 'Setup your workspace', workspace_path, class:'nav-link' %>
  </li>

  <li class="nav-item">
    <%= link_to 'Deal with code', code_path, class:'nav-link' %>
  </li>

  <li class="nav-item">
    <%= link_to 'Submit changes', changes_path, class:'nav-link' %>
  </li>

  <li class="nav-item">
    <%= link_to 'Success Stories', success_stories_path, class:'nav-link' %>
  </li>


  <li>
    <% if @project.owner?(current_user) %>
      <div class="nav nav-tabs dropdown btn btn-primary">
        <button type="button" class="float-right dropdown-toggle btn btn-primary" data-toggle="dropdown">Administration menu
        </button>
        <div class="dropdown-menu dropdown-menu-right" role="menu">
          <%= link_to "Edit project", edit_project_path(@project), class: "dropdown-item" %>
          <%= link_to "Owners", project_users_path(@project), class: "dropdown-item" %>
          <a href="<%=edit_project_path(@project)%>#status" class="dropdown-item">Deactivate project</a>
        </div>
      </div>
    <% end %>
  </li>
  
</ul>
<hr>
</div>



<!--MODIFICANDO A PARTIR DAQUI-->
<div class="page-content container-fluid tab-content">
  <div class="tab-pane fade show active" id="pills-about" role="tabpanel">
    <% tab_pane(:about, active: true) do %>
      <%= render @project.widgets.from_tab(:about ) %>
    <% end %>
    <!--END OF CONTENT FOR TAB 1-->
  </div>

  <div class="tab-pane fade" id="pills-start" role="tabpanel">
  </div>

  <div class="tab-pane fade" id="pills-community" role="tabpanel">
    
  </div>


  <div class="tab-pane fade" id="pills-workspace" role="tabpanel">    
    
  </div>


  <div class="tab-pane fade" id="pills-code" role="tabpanel">
    <%= link_to 'Deal with code', code_path %>
  </div>


  <div class="tab-pane fade" id="pills-changes" role="tabpanel">
    <%= link_to 'Submit your changes', changes_path %>
  </div>

</div>

<%else%>
  <%= render 'visitor/header' unless current_user %>
  <%= render 'visitor/menu' unless current_user %>

  <div id="<%= @project.id %>" class="page-header page-header-bordered page-header-tabs  nav-tabs-horizontal" data-plugin="tabs">
  <%= render 'notices' %>
  <figure class='logo-projeto text-center'>
    <img class=" img-responsive" src="<%= @project.image_url %>"
    style="max-width:250px;"/>
  </figure>
  <h1 class="page-title text-center"><%= @project.name %>
    <% if @project.recent? %>
      <span class="badge badge-danger badge-sm">New</span>
    <% end %>
  </h1>
  <p class="tags text-center">
    <% @project.tags.each do |tag| %>
      <%= link_to projects_path(search: tag.to_s) do %>
        <span class="badge badge-outline badge-primary"><%=tag.to_s%></span>
      <% end %>
    <% end %>
  </p>
  <p class='text-center'><%= @project.description %></p>
  <div class="text-center">
    <small>Project created <%= time_ago_in_words @project.created_at %> ago</small>
  </div>
    <div class="nav nav-tabs float-right" role="tablist">

      <% if @project.owner?(current_user) %>

        <div class="nav nav-tabs dropdown">
          <button type="button" class="float-right btn btn-primary dropdown-toggle float-right waves-effect waves-classic" data-toggle="dropdown">
          Administration menu
          </button>
          <div class="dropdown-menu dropdown-menu-right" role="menu">
            <%= link_to "Edit project", edit_project_path(@project), class: "dropdown-item" %>
            <%= link_to "Owners", project_users_path(@project), class: "dropdown-item" %>
            <a href="<%=edit_project_path(@project)%>#status" class="dropdown-item">Activate project</a>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="page-content container-fluid" style="background-color: white; padding: 30px;">
    <div class="row">
      <div class="col"></div>
      <div class="col-lg">
        <h4>This project is currently inactive.</h4>
        <h4>If you own this project and want to reactivate it, please visit the administration menu</h4>
      </div>
      <div class="col"></div>
    </div>
  </div>
  <%= render 'application/footer' unless current_user %>

<%end%>
 